# -*- coding: utf-8 -*-
"""Copy of Tool_extract specific rows.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kTzQ0BA6PcNnv2A15I12dELRrQbw5r1L
"""

import pandas as pd
import numpy as np
!pip install pivottablejs
from pivottablejs import pivot_ui
from IPython.display import HTML
from IPython.display import IFrame
import json, io

from google.colab import drive
drive.mount('/content/drive')

df1 = pd.read_table("/content/drive/MyDrive/Colab Notebooks/WA108_IBDC_29.06.2022/nextstrain_metadata1.tsv", sep='\t')

count_row = df1.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row

df1.columns

nibmg = df1.loc[df1['submitting_lab'] == 'NIBMG']

count_row1 = nibmg.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row1

non_nibmg = df1.loc[df1['submitting_lab'] != 'NIBMG']

count_row2 = non_nibmg.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row2

df2 = pd.read_table("/content/drive/MyDrive/Colab Notebooks/WA108_IBDC_29.06.2022/nextstrain_metadata2.tsv", sep='\t')

count_row3 = df2.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row3

# df1 = pd.read_table("/content/drive/MyDrive/Colab Notebooks/WA_101_IBDC/subsample/insacog_metadata_v3.1.tsv", sep='\t')

nibmg = df2.loc[df2['submitting_lab'] == 'NIBMG']

count_row4 = nibmg.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row4

nibmg.columns

df3 = pd.concat([non_nibmg, nibmg], ignore_index=True, sort=False)

df3 = pd.concat([non_nibmg, nibmg], join="inner")

count_row3 = df3.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row3

df3.columns

df3.to_csv('NIBMG_IBDC_combined_metadata_v2.tsv', sep="\t", index=False)