# -*- coding: utf-8 -*-
"""Tool_2df_join_Column-wise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hg6CUBzxdtHoIyKuLdXUHOqibTZE5Xk
"""

import pandas as pd
import numpy as np
!pip install pivottablejs
from pivottablejs import pivot_ui
from IPython.display import HTML
from IPython.display import IFrame
import json, io

from google.colab import drive
drive.mount('/content/drive')

df1 = pd.read_table("/content/drive/MyDrive/Colab Notebooks/WA102_WHO/nextstrain_metadata.tsv", sep='\t')

df1.head(1)

count_row = df1.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row

# count_row = df1.shape[0]  # Gives number of rows
count_col = df1.shape[1]  # Gives number of columns
count_col

df2 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Tools/twodfcolumn/unassigned_N-content.csv")

count_row = df2.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row

# count_row = df1.shape[0]  # Gives number of rows
count_col = df2.shape[1]  # Gives number of columns
count_col

df3 = pd.merge(df1, df2, on='strain', how='outer')

count_row = df3.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row

# count_row = df1.shape[0]  # Gives number of rows
count_col = df3.shape[1]  # Gives number of columns
count_col

df3.head(2)

df3.to_csv('NIBMG_IBDC_Unassigned_metadata.tsv', sep="\t", index=False)