# -*- coding: utf-8 -*-
"""Tool_2df_join_RowF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oiKQFKO_p4OtNMkhoIG9Tt7aJ5-JGdZq
"""

import pandas as pd
import numpy as np
!pip install pivottablejs
from pivottablejs import pivot_ui
from IPython.display import HTML
from IPython.display import IFrame
import json, io

from google.colab import drive
drive.mount('/content/drive')

df1 = pd.read_table("/content/drive/MyDrive/Colab Notebooks/Tools/XBB/nextstrain_metadata_batch70.tsv", sep='\t')

count_row = df1.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row

df2 = pd.read_table("/content/drive/MyDrive/Colab Notebooks/Tools/XBB/2_IBDC_INSACOG-SARS-CoV2-30Aug22_INCREMENT_3911.tsv", sep='\t')

count_row2 = df2.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row2

dfF = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8], join="inner")

count_row3 = dfF.shape[0]  # Gives number of rows
#count_col = df1.shape[1]  # Gives number of columns
count_row3

dfF.to_csv('IBDC_incremental.tsv', sep="\t", index=False)

#upload_query_df
dfQ = pd.read_table("/content/drive/MyDrive/Colab Notebooks/Tools/XBB/WB-XBBv2.tsv", sep='\t')

dfMatch = df1[df1['strain'].isin(dfQ["strain"])]

dfMatch.to_csv('matchedXBB.tsv', sep="\t", index=False)

dfQ.head(2)

# df1[df1['lineage'].isin(df2["lineage"])]

# #df1[~df1['lineage'].isin(df2["lineage"])]

